"use client";
import { useState, FormEvent } from "react";
type Row = Record<string, string | boolean | number>;
export function AdminTools() {
    const [kind, setKind] = useState("users"), [rows, setRows] = useState<Row[]>([]), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
    async function load(value: string) { setKind(value); setBusy(true); setMessage(""); try { const j = await (await fetch("/api/admin/manage?kind=" + value)).json(); if (!j.success) throw new Error(j.message); setRows(j.data || []); } catch (e) { setRows([]); setMessage(e instanceof Error ? e.message : "โหลดไม่สำเร็จ"); } finally { setBusy(false); } }
    async function save(kind: string, data: Row) { setBusy(true); setMessage(""); try { const j = await (await fetch("/api/admin/manage", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, data }) })).json(); if (!j.success) throw new Error(j.message); setMessage("บันทึกแล้ว"); } catch (e) { setMessage(e instanceof Error ? e.message : "บันทึกไม่สำเร็จ"); } finally { setBusy(false); } }
    function submit(e: FormEvent<HTMLFormElement>, type: string) { e.preventDefault(); void save(type, Object.fromEntries(Array.from(new FormData(e.currentTarget), ([k, v]) => [k, String(v)]))); }
    return <section className="panel admin-tools"><h2>จัดการระบบ</h2><div className="toolbar">{[["users", "บัญชีผู้ใช้"], ["rooms", "ห้อง"], ["audit", "ประวัติ"]].map(([v, label]) => <button key={v} className="button button-secondary" disabled={busy} onClick={() => load(v)}>{label}</button>)}</div><p role="status">{message || "เลือกหมวดเพื่อโหลดข้อมูล"}</p>{kind === "users" && <><p>แอดมินหลักใช้บัญชีจากการตั้งค่าระบบ บัญชีสมาชิกด้านล่างปรับสิทธิ์ ปิดใช้งาน และตั้งรหัสผ่านใหม่ได้</p>{rows.map(u => <form className="management-row" key={String(u.id)} onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(Array.from(new FormData(e.currentTarget), ([k, v]) => [k, String(v)])); void save("user", { ...d, id: u.id, active: d.active === "true" }); }}><strong>{u.username} — {u.name}</strong><select name="role" aria-label="บทบาท" defaultValue={String(u.role)}><option value="user">User</option><option value="admin">Admin</option></select><select name="active" aria-label="สถานะบัญชี" defaultValue={String(u.active)}><option value="true">เปิดใช้งาน</option><option value="false">ปิดใช้งาน</option></select><input name="password" type="password" aria-label="รหัสผ่านใหม่" placeholder="รหัสผ่านใหม่ (เว้นว่างได้)" minLength={10} /><button disabled={busy} className="button button-primary">บันทึก</button></form>)}
        <h3>ระบุเจ้าของรายการเดิม</h3><p>ตรวจสอบเจ้าของก่อนผูกบัญชี รายการเก่าจะยังไม่ปรากฏให้สมาชิกจนกว่าจะกำหนดเจ้าของ</p><form className="management-row" onSubmit={e => submit(e, "owner")}><input name="id" aria-label="รหัสการจอง" placeholder="รหัสการจอง" required /><select name="user_id" aria-label="เจ้าของรายการ" required><option value="">เลือกสมาชิก</option>{rows.map(u => <option key={String(u.id)} value={String(u.id)}>{u.username} — {u.name}</option>)}</select><button className="button button-primary" disabled={busy}>ผูกเจ้าของ</button></form></>}
        {kind === "rooms" && <><p>ใช้หมายเลขห้องเดิมเพื่อแก้ไข หรือหมายเลขใหม่เพื่อเพิ่มห้อง การปิดห้องไม่ลบประวัติการจอง</p><form className="management-row" onSubmit={e => submit(e, "room")}><input name="room_number" placeholder="หมายเลขห้อง" aria-label="หมายเลขห้อง" required pattern="[0-9]{1,10}" /><input name="room_name" placeholder="ชื่อห้อง" aria-label="ชื่อห้อง" required /><select name="status" aria-label="สถานะห้อง"><option value="available">เปิดจอง</option><option value="unavailable">ปิดจอง</option></select><button className="button button-primary" disabled={busy}>บันทึกห้อง</button></form>{rows.map(r => <p key={String(r.id)}>{r.room_number} — {r.room_name} — {r.status === "available" ? "เปิดจอง" : "ปิดจอง"}</p>)}</>}
        {kind === "audit" && <div className="audit-list">{rows.map((r, i) => <p key={i}>{r.timestamp} · {r.booking_id} · {r.action} · {r.actor}<br />{r.detail}</p>)}</div>}</section>
}
