"use client";
import { FormEvent,useState } from "react";
import type { ApiResponse,Booking } from "@/lib/types";
import { StatusBadge } from "./status-badge";

export function MyBookings() {
  const [credentials,setCredentials] = useState({id:"",student_id:""}); const [item,setItem] = useState<Booking|null>(null); const [loading,setLoading] = useState(false); const [error,setError] = useState("");
  async function run(action:"lookup"|"cancel") {setLoading(true);setError("");try{const r=await fetch("/api/bookings/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...credentials,action})});const result:ApiResponse<Booking>=await r.json();if(!result.success)throw new Error(result.message);setItem(result.data||null);}catch(e){setError(e instanceof Error?e.message:"ดำเนินการไม่สำเร็จ");}finally{setLoading(false);}}
  async function search(event:FormEvent){event.preventDefault();await run("lookup");}
  async function cancel(){if(!window.confirm("ยืนยันยกเลิกการจองรายการนี้ใช่หรือไม่"))return;await run("cancel");}
  return <><form className="panel lookup-card" onSubmit={search}><h2>ตรวจสอบการจอง</h2><p className="lookup-help">ใช้รหัสการจองที่ได้รับหลังส่งคำขอร่วมกับรหัสนักศึกษา</p><div className="lookup-fields"><div className="field"><label htmlFor="booking-id">รหัสการจอง</label><input id="booking-id" required value={credentials.id} onChange={(e)=>setCredentials({...credentials,id:e.target.value.toUpperCase()})} placeholder="เช่น BK20260907123456ABCD" /></div><div className="field"><label htmlFor="lookup-student-id">รหัสนักศึกษา</label><input id="lookup-student-id" required inputMode="numeric" value={credentials.student_id} onChange={(e)=>setCredentials({...credentials,student_id:e.target.value.replace(/\D/g,"")})} placeholder="กรอกรหัสนักศึกษา" /></div><button className="button button-primary" disabled={loading}>{loading?"กำลังตรวจสอบ…":"ตรวจสอบสถานะ"}</button></div>{error&&<p className="form-message error">{error}</p>}</form>{item&&<article className="booking-detail"><div className="booking-detail-head"><div><span>รหัส {item.id}</span><h2>ห้อง {item.room}</h2></div><StatusBadge status={item.status}/></div><dl><div><dt>วันที่และเวลา</dt><dd>{item.booking_date} · {item.start_time}–{item.end_time} น.</dd></div><div><dt>วัตถุประสงค์</dt><dd>{item.purpose}</dd></div>{item.status_reason&&<div><dt>เหตุผล/หมายเหตุ</dt><dd>{item.status_reason}</dd></div>}</dl>{["pending","approved"].includes(item.status)&&<button className="button button-danger" onClick={cancel} disabled={loading}>{loading?"กำลังยกเลิก…":"ยกเลิกการจอง"}</button>}</article>}</>;
}
